apiVersion: v2
name: evcc-kubernetes
description: Installs evcc in Kubernetes

type: application
version: 1.7.2

sources:
  - https://evcc.io/
  - https://kubernetes.io/
  - https://github.com/evcc-io
  - https://github.com/evcc-io/evcc
appVersion: "0.314.2"
maintainers:
  - name: cooling75
